### PR TITLE
improve syntax of json example

### PR DESCRIPTION
**Pull request by harlantwood**
cc @ig-shaun

### CODE REVIEW

**Review by TimDaub — APPROVED** [review]

**Comment by ChristopherA** [comment]
Shouldn't this file be in /drafts?

**Comment by TimDaub** [comment]
> Shouldn't this file be in /drafts?

@ig-shaun or I will move it there soon.

**Comment by TimDaub** [comment]
Thanks @harlantwood :tada:

**Comment by harlantwood** [comment]
Sure!

**Pull request merged**
